import { FloodEvent } from '../types';
import { HcmcQuadrant, RollingPrecipitation } from './weatherService';
import { calculateAstronomicalTideDepth, getSaigonTideStatus } from './tideService';
import { evaluateCompoundFloodRisk } from './predictionEngine';

export interface EnhancedVulnerableCorridor {
  id: string;
  streetName: string;
  district: string;
  city: string;
  quadrant: HcmcQuadrant;
  drainageBasin: 'Nam Sài Gòn' | 'Đông Sài Gòn' | 'Tây Bắc' | 'Tây Nam' | 'Trung tâm';
  primaryCause: 'heavy_rain' | 'high_tide' | 'combined';
  rainThresholdMm: number;    // Rainfall threshold in mm/h that overwhelms drainage
  tideThresholdM: number;     // River tide level at Phu An station that triggers flooding (m)
  baseDepthCm: number;        // Typical inundation depth during standard overflow (cm)
  coordinate: [number, number]; // [lng, lat]
  description: string;
}

// Backward compatibility alias
export type VulnerableCorridor = EnhancedVulnerableCorridor;

export const HCMC_VULNERABLE_CORRIDORS: EnhancedVulnerableCorridor[] = [
  // --- LƯU VỰC NAM SÀI GÒN (15 corridors) ---
  {
    id: 'corridor-tran-xuan-soan',
    streetName: 'Trần Xuân Soạn',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.50,
    baseDepthCm: 50,
    coordinate: [106.7082, 10.7485],
    description: 'Bờ kè Kênh Tẻ ngập sâu khi triều cường kết hợp mưa',
  },
  {
    id: 'corridor-huynh-tan-phat',
    streetName: 'Huỳnh Tấn Phát',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.52,
    baseDepthCm: 45,
    coordinate: [106.7325, 10.7349],
    description: 'Đoạn ngã tư Nguyễn Thị Thập và cầu Phú Xuân trũng thấp',
  },
  {
    id: 'corridor-le-van-luong-q7',
    streetName: 'Lê Văn Lương',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 25,
    tideThresholdM: 1.48,
    baseDepthCm: 45,
    coordinate: [106.7011, 10.7412],
    description: 'Đoạn qua rạch Đỉa và rạch Ông Lớn',
  },
  {
    id: 'corridor-nguyen-thi-thap',
    streetName: 'Nguyễn Thị Thập',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.6960, 10.7390],
    description: 'Đoạn ngã ba Nguyễn Hữu Thọ - Nguyễn Thị Thập',
  },
  {
    id: 'corridor-pham-hung',
    streetName: 'Phạm Hùng',
    district: 'Quận 8',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 35,
    tideThresholdM: 1.55,
    baseDepthCm: 35,
    coordinate: [106.6750, 10.7380],
    description: 'Chân cầu Chánh Hưng thường ngập lúc đỉnh triều',
  },
  {
    id: 'corridor-duong-ba-trac',
    streetName: 'Dương Bá Trạc',
    district: 'Quận 8',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 30,
    tideThresholdM: 1.52,
    baseDepthCm: 40,
    coordinate: [106.6883, 10.7489],
    description: 'Đoạn chân cầu Kênh Xáng nối Quận 7 và Quận 8',
  },
  {
    id: 'corridor-ben-phu-dinh',
    streetName: 'Bến Phú Định',
    district: 'Quận 8',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 30,
    tideThresholdM: 1.48,
    baseDepthCm: 50,
    coordinate: [106.6280, 10.7250],
    description: 'Khu vực bến sông ven kênh Đôi tràn bờ bao thường xuyên',
  },
  {
    id: 'corridor-me-coc',
    streetName: 'Mễ Cốc',
    district: 'Quận 8',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 30,
    tideThresholdM: 1.48,
    baseDepthCm: 55,
    coordinate: [106.6295, 10.7215],
    description: 'Tuyến đê bao Mễ Cốc thường xuyên quá tải đỉnh triều',
  },
  {
    id: 'corridor-ton-that-thuyet',
    streetName: 'Tôn Thất Thuyết',
    district: 'Quận 4',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 35,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.7050, 10.7580],
    description: 'Tuyến đường dọc Kênh Tẻ bờ Quận 4',
  },
  {
    id: 'corridor-doan-van-bo',
    streetName: 'Đoàn Văn Bơ',
    district: 'Quận 4',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 25,
    tideThresholdM: 1.58,
    baseDepthCm: 35,
    coordinate: [106.7020, 10.7600],
    description: 'Khu dân cư trũng thấp đoạn chân cầu Đoàn Văn Bơ',
  },
  {
    id: 'corridor-nguyen-khoai',
    streetName: 'Nguyễn Khoái',
    district: 'Quận 4',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 35,
    coordinate: [106.7070, 10.7540],
    description: 'Đoạn giao Tôn Thất Thuyết ra bến tàu',
  },
  {
    id: 'corridor-dao-tri',
    streetName: 'Đào Trí',
    district: 'Quận 7',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 30,
    tideThresholdM: 1.48,
    baseDepthCm: 45,
    coordinate: [106.7420, 10.7280],
    description: 'Tuyến đường ven sông Soài Rạp ngập nặng lúc triều lên',
  },
  {
    id: 'corridor-nguyen-binh',
    streetName: 'Nguyễn Bình',
    district: 'Nhà Bè',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 30,
    tideThresholdM: 1.48,
    baseDepthCm: 45,
    coordinate: [106.7060, 10.6720],
    description: 'Đoạn trung tâm huyện Nhà Bè giáp rạch Tôm',
  },
  {
    id: 'corridor-le-van-luong-nha-be',
    streetName: 'Lê Văn Lương (Nhà Bè)',
    district: 'Nhà Bè',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'high_tide',
    rainThresholdMm: 25,
    tideThresholdM: 1.45,
    baseDepthCm: 50,
    coordinate: [106.7040, 10.6950],
    description: 'Đoạn qua các cầu Rạch Đỉa, Long Kiểng, Rạch Tôm trũng thấp',
  },
  {
    id: 'corridor-pham-the-hien',
    streetName: 'Phạm Thế Hiển',
    district: 'Quận 8',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'south',
    drainageBasin: 'Nam Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.6540, 10.7350],
    description: 'Đoạn chợ Rạch Ông và xóm đạo Quận 8',
  },

  // --- LƯU VỰC ĐÔNG SÀI GÒN (15 corridors) ---
  {
    id: 'corridor-vo-van-ngan',
    streetName: 'Võ Văn Ngân',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.65,
    baseDepthCm: 55,
    coordinate: [106.7570, 10.8520],
    description: 'Độ dốc địa hình lớn tạo dòng nước xiết đổ về chợ Thủ Đức',
  },
  {
    id: 'corridor-to-ngoc-van',
    streetName: 'Tô Ngọc Vân',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.65,
    baseDepthCm: 45,
    coordinate: [106.7450, 10.8650],
    description: 'Điểm trũng ngập đoạn giao cắt đường sắt Bắc Nam',
  },
  {
    id: 'corridor-quoc-huong',
    streetName: 'Quốc Hương',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 25,
    tideThresholdM: 1.50,
    baseDepthCm: 50,
    coordinate: [106.7326, 10.8038],
    description: 'Khu vực Thảo Điền hạ tầng trũng thấp',
  },
  {
    id: 'corridor-thao-dien',
    streetName: 'Thảo Điền',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 25,
    tideThresholdM: 1.50,
    baseDepthCm: 45,
    coordinate: [106.7360, 10.8030],
    description: 'Đoạn ngã ba Thảo Điền - Xuân Thủy',
  },
  {
    id: 'corridor-nguyen-van-huong',
    streetName: 'Nguyễn Văn Hưởng',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 25,
    tideThresholdM: 1.50,
    baseDepthCm: 45,
    coordinate: [106.7350, 10.8120],
    description: 'Bờ bao bán đảo Thảo Điền sát sông Sài Gòn',
  },
  {
    id: 'corridor-kha-van-can',
    streetName: 'Kha Vạn Cân',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.65,
    baseDepthCm: 45,
    coordinate: [106.7450, 10.8520],
    description: 'Đoạn chân cầu vượt Linh Xuân và đường sắt',
  },
  {
    id: 'corridor-do-xuan-hop',
    streetName: 'Đỗ Xuân Hợp',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.65,
    baseDepthCm: 50,
    coordinate: [106.7780, 10.8120],
    description: 'Đoạn qua phường Phước Long B trũng thấp kinh niên',
  },
  {
    id: 'corridor-le-van-viet',
    streetName: 'Lê Văn Việt',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 32,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.7820, 10.8460],
    description: 'Đoạn ngã tư Đình và Man Thiện',
  },
  {
    id: 'corridor-la-xuan-oai',
    streetName: 'Lã Xuân Oai',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.65,
    baseDepthCm: 45,
    coordinate: [106.7910, 10.8250],
    description: 'Đoạn gần cầu Tăng Long trũng thấp',
  },
  {
    id: 'corridor-tam-binh',
    streetName: 'Tam Bình',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.7410, 10.8710],
    description: 'Đoạn giao cắt Tô Ngọc Vân vào chợ Tam Hà',
  },
  {
    id: 'corridor-hiep-binh',
    streetName: 'Hiệp Bình',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 28,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.7260, 10.8350],
    description: 'Đoạn gần ngã ba Hiệp Bình - Phạm Văn Đồng',
  },
  {
    id: 'corridor-go-dua',
    streetName: 'Gò Dưa',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.7380, 10.8680],
    description: 'Khu vực phường Tam Bình giáp ranh Bình Dương',
  },
  {
    id: 'corridor-duong-van-cam',
    streetName: 'Dương Văn Cam',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.65,
    baseDepthCm: 50,
    coordinate: [106.7590, 10.8540],
    description: 'Rốn ngập khu vực chợ Thủ Đức',
  },
  {
    id: 'corridor-dang-thi-ranh',
    streetName: 'Đặng Thị Rành',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.65,
    baseDepthCm: 50,
    coordinate: [106.7580, 10.8530],
    description: 'Cửa ngõ thoát nước trũng quanh nhà lồng chợ Thủ Đức',
  },
  {
    id: 'corridor-luong-dinh-cua',
    streetName: 'Lương Định Của',
    district: 'TP. Thủ Đức',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Đông Sài Gòn',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.7350, 10.7920],
    description: 'Đoạn ngã ba Trần Não vào khu đô thị Thủ Thiêm',
  },

  // --- LƯU VỰC TÂY BẮC (15 corridors) ---
  {
    id: 'corridor-phan-huy-ich',
    streetName: 'Phan Huy Ích',
    district: 'Gò Vấp',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.68,
    baseDepthCm: 45,
    coordinate: [106.6340, 10.8350],
    description: 'Vùng trũng ảnh hưởng lưu vực kênh Tham Lương',
  },
  {
    id: 'corridor-le-duc-tho',
    streetName: 'Lê Đức Thọ',
    district: 'Gò Vấp',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 35,
    tideThresholdM: 1.68,
    baseDepthCm: 40,
    coordinate: [106.6710, 10.8450],
    description: 'Điểm trũng ngập đoạn ngã tư Lê Đức Thọ - Nguyễn Oanh',
  },
  {
    id: 'corridor-nguyen-van-khoi',
    streetName: 'Nguyễn Văn Khối',
    district: 'Gò Vấp',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.68,
    baseDepthCm: 45,
    coordinate: [106.6540, 10.8480],
    description: 'Đoạn công viên Làng Hoa trũng thấp kinh niên',
  },
  {
    id: 'corridor-pham-van-chieu',
    streetName: 'Phạm Văn Chiêu',
    district: 'Gò Vấp',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.68,
    baseDepthCm: 45,
    coordinate: [106.6500, 10.8530],
    description: 'Đoạn từ Lê Văn Thọ đến Cây Trâm ngập kinh niên',
  },
  {
    id: 'corridor-le-van-tho',
    streetName: 'Lê Văn Thọ',
    district: 'Gò Vấp',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.68,
    baseDepthCm: 40,
    coordinate: [106.6580, 10.8460],
    description: 'Khu vực công viên Làng Hoa đến chợ Xóm Mới',
  },
  {
    id: 'corridor-nguyen-van-qua',
    streetName: 'Nguyễn Văn Quá',
    district: 'Quận 12',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.68,
    baseDepthCm: 55,
    coordinate: [106.6273, 10.8415],
    description: 'Đoạn chợ Cầu quá tải cống hộp thường xuyên tê liệt khi mưa to',
  },
  {
    id: 'corridor-song-hanh-ql22',
    streetName: 'Song Hành Quốc Lộ 22',
    district: 'Quận 12',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 35,
    tideThresholdM: 1.68,
    baseDepthCm: 40,
    coordinate: [106.6110, 10.8570],
    description: 'Khu vực giáp Hóc Môn thu nước mặt đường diện rộng',
  },
  {
    id: 'corridor-phan-van-hon',
    streetName: 'Phan Văn Hớn',
    district: 'Quận 12',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.68,
    baseDepthCm: 45,
    coordinate: [106.6150, 10.8380],
    description: 'Đoạn qua chợ Tân Thới Nhất và cầu Bà Bếp',
  },
  {
    id: 'corridor-ha-huy-giap',
    streetName: 'Hà Huy Giáp',
    district: 'Quận 12',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.6780, 10.8750],
    description: 'Tuyến đê bao sông Sài Gòn phía bờ Quận 12',
  },
  {
    id: 'corridor-ql1a-tan-thoi-hiep',
    streetName: 'Quốc Lộ 1A (Tân Thới Hiệp)',
    district: 'Quận 12',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 35,
    tideThresholdM: 1.68,
    baseDepthCm: 40,
    coordinate: [106.6450, 10.8620],
    description: 'Chân cầu vượt Tân Thới Hiệp ngập làn xe máy',
  },
  {
    id: 'corridor-phan-anh',
    streetName: 'Phan Anh',
    district: 'Tân Phú',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.68,
    baseDepthCm: 50,
    coordinate: [106.6220, 10.7680],
    description: 'Rốn ngập giáp ranh Tân Phú và Bình Tân',
  },
  {
    id: 'corridor-tan-ky-tan-quy',
    streetName: 'Tân Kỳ Tân Quý',
    district: 'Tân Phú',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.68,
    baseDepthCm: 40,
    coordinate: [106.6280, 10.7980],
    description: 'Đoạn từ Lê Trọng Tấn đến kênh Tham Lương',
  },
  {
    id: 'corridor-dong-den',
    streetName: 'Đồng Đen',
    district: 'Tân Bình',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.68,
    baseDepthCm: 45,
    coordinate: [106.6450, 10.7950],
    description: 'Khu Bàu Cát trũng thấp đoạn giao Bàu Cát 2',
  },
  {
    id: 'corridor-bau-cat',
    streetName: 'Bàu Cát',
    district: 'Tân Bình',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.68,
    baseDepthCm: 40,
    coordinate: [106.6480, 10.7920],
    description: 'Đoạn công viên Bàu Cát và chợ Bàu Cát',
  },
  {
    id: 'corridor-au-co',
    streetName: 'Âu Cơ',
    district: 'Tân Bình',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'northwest',
    drainageBasin: 'Tây Bắc',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 32,
    tideThresholdM: 1.68,
    baseDepthCm: 35,
    coordinate: [106.6520, 10.7820],
    description: 'Đoạn giao Lạc Long Quân và Trịnh Đình Trọng',
  },

  // --- LƯU VỰC TÂY NAM (13 corridors) ---
  {
    id: 'corridor-ho-hoc-lam',
    streetName: 'Hồ Học Lãm',
    district: 'Bình Tân',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.60,
    baseDepthCm: 50,
    coordinate: [106.6180, 10.7220],
    description: 'Đoạn nối An Dương Vương ra đại lộ Võ Văn Kiệt',
  },
  {
    id: 'corridor-an-duong-vuong',
    streetName: 'An Dương Vương',
    district: 'Quận 8',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.6250, 10.7300],
    description: 'Vùng trũng giáp ranh Quận 8 và Bình Tân',
  },
  {
    id: 'corridor-kinh-duong-vuong',
    streetName: 'Kinh Dương Vương',
    district: 'Bình Tân',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 35,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.6210, 10.7420],
    description: 'Khu vực bến xe Miền Tây và vòng xoay An Lạc',
  },
  {
    id: 'corridor-hau-giang',
    streetName: 'Hậu Giang',
    district: 'Quận 6',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.60,
    baseDepthCm: 40,
    coordinate: [106.6410, 10.7510],
    description: 'Đoạn chợ Cây Gõ và cầu Hậu Giang',
  },
  {
    id: 'corridor-ba-hom',
    streetName: 'Bà Hom',
    district: 'Quận 6',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.6280, 10.7550],
    description: 'Đoạn chợ Phú Lâm ra vòng xoay Phú Lâm',
  },
  {
    id: 'corridor-tan-hoa-dong',
    streetName: 'Tân Hòa Đông',
    district: 'Quận 6',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.65,
    baseDepthCm: 45,
    coordinate: [106.6320, 10.7620],
    description: 'Khu vực kênh Tân Hóa - Lò Gốm trũng thấp',
  },
  {
    id: 'corridor-binh-phu',
    streetName: 'Bình Phú',
    district: 'Quận 6',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.60,
    baseDepthCm: 40,
    coordinate: [106.6350, 10.7450],
    description: 'Khu dân cư Bình Phú đoạn công viên',
  },
  {
    id: 'corridor-tran-van-kieu',
    streetName: 'Trần Văn Kiểu',
    district: 'Quận 6',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.60,
    baseDepthCm: 35,
    coordinate: [106.6360, 10.7420],
    description: 'Đoạn nối đại lộ Võ Văn Kiệt vào khu Bình Phú',
  },
  {
    id: 'corridor-hong-bang',
    streetName: 'Hồng Bàng',
    district: 'Quận 6',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 32,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.6480, 10.7540],
    description: 'Đoạn ngã ba Hồng Bàng - Minh Phụng',
  },
  {
    id: 'corridor-lac-long-quan',
    streetName: 'Lạc Long Quân',
    district: 'Quận 11',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.6470, 10.7690],
    description: 'Đoạn trước cổng công viên văn hóa Đầm Sen',
  },
  {
    id: 'corridor-hoa-binh',
    streetName: 'Hòa Bình',
    district: 'Quận 11',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 28,
    tideThresholdM: 1.65,
    baseDepthCm: 45,
    coordinate: [106.6380, 10.7710],
    description: 'Rốn ngập trước cổng 1A Đầm Sen',
  },
  {
    id: 'corridor-ten-lua',
    streetName: 'Tên Lửa',
    district: 'Bình Tân',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 35,
    tideThresholdM: 1.65,
    baseDepthCm: 35,
    coordinate: [106.6080, 10.7550],
    description: 'Khu vực Aeon Mall Bình Tân đoạn giao Tỉnh Lộ 10',
  },
  {
    id: 'corridor-ma-lo',
    streetName: 'Mã Lò',
    district: 'Bình Tân',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Tây Nam',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.65,
    baseDepthCm: 40,
    coordinate: [106.6020, 10.7680],
    description: 'Đoạn từ Lê Văn Quới đến bệnh viện Bình Tân',
  },

  // --- LƯU VỰC TRUNG TÂM (10 corridors) ---
  {
    id: 'corridor-ung-van-khiem',
    streetName: 'Ung Văn Khiêm',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.58,
    baseDepthCm: 45,
    coordinate: [106.7170, 10.8080],
    description: 'Đoạn ngã ba Ung Văn Khiêm - D2 Nguyễn Gia Trí',
  },
  {
    id: 'corridor-nguyen-huu-canh',
    streetName: 'Nguyễn Hữu Cảnh',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'combined',
    rainThresholdMm: 35,
    tideThresholdM: 1.55,
    baseDepthCm: 45,
    coordinate: [106.7180, 10.7915],
    description: 'Lòng chảo chân cầu Thủ Thiêm',
  },
  {
    id: 'corridor-nguyen-gia-tri',
    streetName: 'Nguyễn Gia Trí',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'east',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 20,
    tideThresholdM: 1.60,
    baseDepthCm: 60,
    coordinate: [106.7145, 10.8035],
    description: 'Vùng trũng rạch Văn Thánh cứ mưa to là ngập sâu',
  },
  {
    id: 'corridor-dinh-bo-linh',
    streetName: 'Đinh Bộ Lĩnh',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.60,
    baseDepthCm: 45,
    coordinate: [106.7090, 10.8070],
    description: 'Đoạn từ cầu Đinh Bộ Lĩnh đến đường Bạch Đằng',
  },
  {
    id: 'corridor-bach-dang',
    streetName: 'Bạch Đằng',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 25,
    tideThresholdM: 1.60,
    baseDepthCm: 40,
    coordinate: [106.7020, 10.8020],
    description: 'Khu vực chợ Bà Chiểu đến ngã tư Hàng Xanh',
  },
  {
    id: 'corridor-xo-viet-nghe-tinh',
    streetName: 'Xô Viết Nghệ Tĩnh',
    district: 'Bình Thạnh',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'combined',
    rainThresholdMm: 30,
    tideThresholdM: 1.55,
    baseDepthCm: 40,
    coordinate: [106.7110, 10.8010],
    description: 'Đoạn ngã năm Đài Liệt Sĩ đến chân cầu Bình Triệu',
  },
  {
    id: 'corridor-nguyen-van-cu',
    streetName: 'Nguyễn Văn Cừ',
    district: 'Quận 5',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 35,
    tideThresholdM: 1.65,
    baseDepthCm: 35,
    coordinate: [106.6823, 10.7626],
    description: 'Đoạn trước trường ĐH Khoa Học Tự Nhiên và ngã tư Trần Hưng Đạo',
  },
  {
    id: 'corridor-calmette',
    streetName: 'Calmette',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'high_tide',
    rainThresholdMm: 35,
    tideThresholdM: 1.58,
    baseDepthCm: 35,
    coordinate: [106.6990, 10.7690],
    description: 'Chân cầu Calmette ven đại lộ Võ Văn Kiệt',
  },
  {
    id: 'corridor-phan-dinh-phung',
    streetName: 'Phan Đình Phùng',
    district: 'Phú Nhuận',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 32,
    tideThresholdM: 1.65,
    baseDepthCm: 35,
    coordinate: [106.6850, 10.7980],
    description: 'Đoạn gần cầu Kiệu và ngã tư Phú Nhuận',
  },
  {
    id: 'corridor-thach-thi-thanh',
    streetName: 'Thạch Thị Thanh',
    district: 'Quận 1',
    city: 'TP. Hồ Chí Minh',
    quadrant: 'center',
    drainageBasin: 'Trung tâm',
    primaryCause: 'heavy_rain',
    rainThresholdMm: 30,
    tideThresholdM: 1.65,
    baseDepthCm: 35,
    coordinate: [106.6910, 10.7910],
    description: 'Đoạn gần chợ Tân Định trũng thấp',
  },
];

/**
 * Backward compatibility: Evaluates rain precipitation against corridors.
 */
export function getRainInducedFloodEvents(
  targetDate: Date,
  rainByQuadrant: Record<HcmcQuadrant, number>
): FloodEvent[] {
  const events: FloodEvent[] = [];

  for (const corridor of HCMC_VULNERABLE_CORRIDORS) {
    let quadrantRain = rainByQuadrant[corridor.quadrant] || 0;
    if (corridor.district === 'Bình Thạnh') {
      quadrantRain = Math.max(rainByQuadrant.center || 0, rainByQuadrant.east || 0);
    }

    if (quadrantRain >= corridor.rainThresholdMm) {
      const rainRatio = quadrantRain / corridor.rainThresholdMm;
      const estimatedDepthCm = Math.min(75, Math.round(corridor.baseDepthCm * Math.sqrt(rainRatio)));

      const startTime = new Date(targetDate.getTime() - 30 * 60 * 1000);
      const peakTime = new Date(targetDate.getTime());
      const endTime = new Date(targetDate.getTime() + 90 * 60 * 1000);

      events.push({
        id: `rain-${corridor.id}`,
        title: `Mưa lớn gây ngập: ${corridor.streetName} (${corridor.district})`,
        sourceType: 'weather_radar',
        cause: 'heavy_rain',
        streetName: corridor.streetName,
        district: corridor.district,
        city: corridor.city,
        startTime,
        peakTime,
        endTime,
        estimatedDepthCm,
        confidenceScore: Math.min(1.0, 0.85 + 0.05 * Math.min(3, rainRatio)),
        geometry: {
          type: 'Point',
          coordinates: corridor.coordinate,
        },
      });
    }
  }

  return events;
}

/**
 * Advanced Multi-Source Flood Evaluator: Combines rolling 3h precipitation,
 * astronomical lunar tide, and tide-locking coupling across all 68+ HCMC corridors.
 */
export function evaluateMultiSourceHotspots(
  targetDate: Date,
  rainByQuadrant: Record<HcmcQuadrant, RollingPrecipitation>
): FloodEvent[] {
  const events: FloodEvent[] = [];
  const tideStatus = getSaigonTideStatus(targetDate);

  for (const corridor of HCMC_VULNERABLE_CORRIDORS) {
    let quadData = rainByQuadrant[corridor.quadrant];
    if (corridor.district === 'Bình Thạnh') {
      const c = rainByQuadrant.center?.effectiveAccumulationMm || 0;
      const e = rainByQuadrant.east?.effectiveAccumulationMm || 0;
      quadData = c >= e ? rainByQuadrant.center : rainByQuadrant.east;
    }

    const rainAccumMm = quadData?.effectiveAccumulationMm || 0;
    const rainProb = quadData?.rainProbability || 0;

    // Calculate rain depth
    let rainDepthCm = 0;
    if (rainAccumMm >= corridor.rainThresholdMm * 0.7) {
      const ratio = rainAccumMm / corridor.rainThresholdMm;
      rainDepthCm = Math.round(corridor.baseDepthCm * Math.sqrt(Math.max(0.2, ratio)));
    }

    // Calculate tide depth
    const tideDepthCm = calculateAstronomicalTideDepth(
      corridor.tideThresholdM,
      targetDate,
      corridor.baseDepthCm
    );

    const isRiverine = corridor.drainageBasin === 'Nam Sài Gòn' || corridor.district === 'Bình Thạnh' || corridor.drainageBasin === 'Đông Sài Gòn';

    const assessment = evaluateCompoundFloodRisk(
      rainProb,
      tideStatus.tideProbability,
      rainDepthCm,
      tideDepthCm,
      isRiverine
    );

    // Only create event if hazard is at least potential (warning tier) or critical
    if (assessment.riskTier !== 'safe' && assessment.estimatedDepthCm >= 10) {
      const startTime = new Date(targetDate.getTime() - 45 * 60 * 1000);
      const peakTime = new Date(targetDate.getTime());
      const endTime = new Date(targetDate.getTime() + 120 * 60 * 1000);

      const cause = (rainDepthCm > 0 && tideDepthCm > 0)
        ? 'combined'
        : (tideDepthCm > 0 ? 'high_tide' : 'heavy_rain');

      events.push({
        id: `predictive-${corridor.id}`,
        title: `${assessment.riskTier === 'critical' ? '🚨 Ngập sâu' : '⚠️ Có khả năng ngập'}: ${corridor.streetName} (${corridor.district})`,
        sourceType: 'weather_radar',
        cause,
        streetName: corridor.streetName,
        district: corridor.district,
        city: corridor.city,
        startTime,
        peakTime,
        endTime,
        estimatedDepthCm: assessment.estimatedDepthCm,
        confidenceScore: assessment.compoundProbability,
        geometry: {
          type: 'Point',
          coordinates: corridor.coordinate,
        },
      });
    }
  }

  return events;
}
